version: "3.7"

services:
  toolhunt:
    container_name: toolhunt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # do not bind mount node_modules
    ports:
      - ${PORT}:${PORT} # set PORT in environment variable
    networks:
      - toolhunt-net
networks:
  toolhunt-net:
    external: true
